[package]
name = "server"
description = "a websocket-server to control lighting fixtures via artnet"
version = "0.1.0"
edition = "2021"

[dependencies]
artnet = { path = "../artnet" }
logger = { path = "../logger" }
config = { path = "../config" }
tungstenite = "0.24.0"
regex = "1.11.0"
