[package]
name = "config"
description = "helpers to parse the yaml configuration file and check if the required fields are present"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
