# configuration file for local testing and development
config:
    server:
      binds: 0.0.0.0:3000
      allow_direct_fixture_control: true
      send_artnet_every_ms: 40
    artnet:
      binds: 0.0.0.0:6454
      sends: 255.255.255.255:6454
      broadcast: true
      universe: 0

fixture_types:
    - name: PAR64
      channels:
          - name: Red
            type: red
          - name: Green
            type: green
          - name: Blue
            type: blue
          - name: White
            type: white
          - name: CTO
            type: fader
          - name: Strobe
            type: fader
          - name: Function
            type: fader
          - name: Dimmer
            type: fader

fixtures:
    - name: par64_1
      start_addr: 1
      type: PAR64

bindings:
    - identifier: color::white
      actions:
          - par64_1.White: 255
          - par64_1.Red: 0
          - par64_1.Green: 0
          - par64_1.Blue: 0

    - identifier: color::{red}{green}{blue}
      actions:
          - par64_1.Red: "{red}"
          - par64_1.Green: "{green}"
          - par64_1.Blue: "{blue}"
    - identifier: dimmer::{dim_val}
      actions:
          - par64_1.Dimmer: "{dim_val}"
          - par64_1.White: 255
